@startuml

entity "PostInfo" {
	* post_id PRIMARY KEY : UUID,
  	--
  	title : TEXT
	description : TEXT
	creatorId : UUID
	createdAt : TIMESTAMP
	updatedAt : TIMESTAMP
	isPrivate : BOOL
	tags : TEXT[]
}

@enduml