# Используем официальный образ PostgreSQL
FROM postgres:latest

# Указываем переменные окружения для конфигурации базы данных
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=YaGnI
ENV POSTGRES_DB=post_service

# При необходимости можно указать дополнительные порты
EXPOSE 2345