CREATE TABLE IF NOT EXISTS user_info (
    user_id UUID PRIMARY KEY,
    login VARCHAR NOT NULL UNIQUE,
    password_hash VARCHAR NOT NULL,
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_additional (
    user_id UUID PRIMARY KEY REFERENCES user_info(user_id) ON DELETE CASCADE,
    name VARCHAR NOT NULL,
    surname VARCHAR NOT NULL,
    birth_date DATE,
    email VARCHAR NOT NULL UNIQUE,
    phone_number VARCHAR
);