@startuml

entity "UserInfo" {
	* user_id PRIMARY KEY : NUMBER
  	--
  	login : VARCHAR
  	password_hash : VARCHAR
	email : VARCHAR
	registered_at : DATETIME
	changed_at: DATETIME
	last_login_time : DATETIME
}

entity "UserAdditional" {
  	* user_id FOREIGN KEY : NUMBER
  	--
	name : VARCHAR
  	surname : VARCHAR
	date_of_birth : DATETIME
	phone_number : VARCHAR
}

UserInfo ||--|| UserAdditional
  
@enduml