@startuml

entity "PostInfo" {
	* post_id PRIMARY KEY : NUMBER
  	--
  	created_user_id FOREIGN KEY : NUMBER
	created_at : DATETIME
	updated_at : DATETIME
	content_url : NUMBER
}

entity "Comments" {
	* post_id FOREIGN KEY : NUMBER
  	--
  	user_id FOREIGN KEY : NUMBER
	post_id FOREIGN KEY : NUMBER
	content : TEXT
	created_at : DATETIME
	updated_at : DATETIME
}

entity "Reactions" {
	* post_id FOREIGN KEY : NUMBER
  	--
  	user_id FOREIGN KEY : NUMBER
	post_id FOREIGN KEY : NUMBER
	type : VARCHAR
	created_at : DATETIME
}

PostInfo ||--o{ Comments
PostInfo ||--o{ Reactions
  
@enduml