@startuml

entity "Event" {
	* event_id PRIMARY KEY : NUMBER
  	--
  	user_id FOREIGN KEY : NUMBER
	event_type : VARCHAR
	time : DATETIME
	event_data : TEXT
}

entity "UserActivity" {
	* user_id FOREIGN KEY : NUMBER
  	--
  	last_login_time : DATETIME
	registered_at : DATETIME
	posts_count : NUMBER
	comments_count : NUMBER
	reactions_count : NUMBER
	watched_posts_count : NUMBER
}

entity "Reactions" {
	* post_id FOREIGN KEY : NUMBER
  	--
  	user_id FOREIGN KEY : NUMBER
	post_id FOREIGN KEY : NUMBER
	type : VARCHAR
	created_at : DATETIME
}

PostInfo ||--o{ Comments
PostInfo ||--o{ Reactions
  
@enduml